.PHONY: clean All

All:
	@echo "----------Building project:[ DaguCar - Release ]----------"
	@$(MAKE) -f  "DaguCar.mk"
clean:
	@echo "----------Cleaning project:[ DaguCar - Release ]----------"
	@$(MAKE) -f  "DaguCar.mk" clean
